### ISSUE TITLE
Support actual copy of drpendencies

### ISSUE THREAD

**Issue by weitzj** [kovetskiy/manul#9]
Hi,

this looks really nice.

Could you clear up a question: What happens if a "vendored" repo in manul's sense is deleted from GitHub? Will manual still work or will it break since it cannot find a dependency?

I am fine with submodules, but I thought vendoring means to be safe in case someone removes their GitHub repo you rely on.

So maybe manul could keep a copy along the submodule.

**Comment by kovetskiy** [comment]
Hi, actually manul is just a smart wrapper around of `git`, so if git repository was deleted from github then `git submodule update` will be failed at next `go get` step.

And as I've noted in readme, copy of vendor source code will provide additional problems:
- It will be nearly impossible to find anything ussing GitHub Search, because you will get many false-positive results;
- Updating dependencies will require manual intervention and commiting a lot of modified lines straight into the main repo;

Actually, you can fork potential problematic repositories to your github profile and change remote uri in .gitmodules file.

**Comment by weitzj** [comment]
Ok. Thank you.
